CREATE OR REPLACE STORAGE INTEGRATION tableau_Integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '${STORAGE_AWS_ROLE_ARN}'
  STORAGE_ALLOWED_LOCATIONS = ('${STORAGE_ALLOWED_LOCATIONS}')
  COMMENT = 'Optional Comment';

-- Describe Integration Object
DESC INTEGRATION tableau_Integration;
